# Generated by Django 4.2.21 on 2025-05-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='certificatNtaionalite',
            new_name='certificatNationalite',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='concoursShouhaiter',
            new_name='concoursSouhaiter',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='extraitNiassance',
            new_name='extraitNaissance',
        ),
    ]
